US-599060 & DEF-686006 & DEF-643025 & DEF-643026 & DEF-659062 & DEF-692139
jenkinsci/hpe-application-automation-tools-plugin pull request #454
Opened 2021-10-26 12:19 UTC by Zsolt-Lukacs22

- Enabling for users to directly use UFT parameters in FS test configurations;
- Improved validation of input parameters;
- Handling case of empty functional tests sets while running tests with ALM Lab;

2021-10-27 13:02 UTC, dorin7bogdan approved these changes

2021-10-28 03:30 UTC, soleverxu commented on HpToolsLauncher/Runners/FileSystemTestsRunner.cs
> +            string paramString = testPath.Substring(testPath.IndexOf("\"", StringComparison.Ordinal)).Trim();
To be honest, I don't like the way to specify the parameters in the test path line. Too many traps here.

Firstly, the double quote `"` is used to split the test path and parameters. As I understood from the code, the only way to make it work is to specify the line like `path/to/test "name1:v1","name2:v2"` which looks not so good. And also it fails the program if I put double quotes around the test path due to the white space in the path.

The second big problem is that the parameter string is split with delimiter `,` and key value pair is split by `:`. The problem is that it may break if those two delimiters `,` and `:` appear in the parameter value, for example, `myurls:http://example.com,https://example.com`.

The possible solution is to provide additional parameters in the parameter file as following:
```
Test1=/path/to/my-test
Test2=/path/to/second-test
Param1_Name1=myurls
Param1_Value1=http://example.com,https://example.com
Param1_Name2=tags
Param1_Value2=web,mobile
Param2_Name1=repo
Param2_Value1=git
```
The above example defines two tests with parameters. The first test `Test1` has two test parameters `myurls = http://example.com,https://example.com` and `tags = web,mobile`. The second test `Test2` has one parameter which is `repo = git`.
The `Param{i}_Name{n}` and `Param{i}_Value{n}` defines the `n`-th parameter of `Test{i}`.

2021-10-28 03:37 UTC, soleverxu requested changes
See comments

2021-10-28 13:05 UTC, Zsolt-Lukacs22 commented on HpToolsLauncher/Runners/FileSystemTestsRunner.cs
> +            string paramString = testPath.Substring(testPath.IndexOf("\"", StringComparison.Ordinal)).Trim();
In the future, it is taken into consideration to separate the path and parameter list definition.

2021-11-01 12:44 UTC, dorin7bogdan approved these changes

2021-11-02 11:29 UTC, dorin7bogdan approved these changes

2021-11-02 11:29 UTC, dorin7bogdan commented on src/main/java/com/microfocus/application/automation/tools/sse/sdk/request/GetTestInstancesRequest.java
> +    public void addId(String id) {
Please refactor the GetTestInstancesRequest class to use constructors instead of properties.
Example:
https://github.com/dorin7bogdan/ADM-TFS-Extension/blob/master/PSModule/AlmLabMgmtClient/SDK/Request/GetTestInstancesRequest.cs

2021-11-02 11:29 UTC, dorin7bogdan commented on src/main/java/com/microfocus/application/automation/tools/sse/sdk/RunManager.java
> +            res = new GetTestSetsRequest(client, args.getEntityId()).execute();
Please update the class GetTestSetsRequest to retrieve only functional tests.
Example:
https://github.com/dorin7bogdan/ADM-TFS-Extension/blob/master/PSModule/AlmLabMgmtClient/SDK/Request/GetTestSetRequest.cs

2021-11-02 11:30 UTC, dorin7bogdan approved these changes

2021-11-03 02:34 UTC, soleverxu reviewed
Need document for limitation

2021-11-03 02:34 UTC, soleverxu commented on HpToolsLauncher/Runners/FileSystemTestsRunner.cs
> +            string paramString = testPath.Substring(testPath.IndexOf("\"", StringComparison.Ordinal)).Trim();
We can leave the current implementation as is, however, please make sure to add the **limitation** document in the plugin page as well as the README file in this repository. The users must know exactly what characters can't appear in the parameter value, and of course the syntax of the parameters line.

2021-11-09 07:24 UTC, merged