Us321046:As a user, in the Jenkins plugin, I can use the execution token instead of username-password for authentication in existing build steps
jenkinsci/hpe-application-automation-tools-plugin pull request #480
Opened 2022-02-22 06:48 UTC by motteww

Please Make sure these boxes are checked before submitting your pull request - Thanks ahead!

- [ ] Proper pull request title - concise and clear for others.
- [ ] Proper pull request short description - clear and concise (as it should appear in the Jira ticket) for other developers and users.
- [ ] Proper Jira ticket - Number, Link in pull request description.
- [ ] The PR can is merged on your machine without any conflicts.
- [ ] The PR can is built on your machine without any (new) warnings.
- [ ] The PR passed sanity tests by you / QA / DevTest / Good Samaritan.
- [ ] Add unit tests with new features.
- [ ] If you added any dependency to the POM - Please update grount

2022-02-22 13:19 UTC, dorin7bogdan reviewed
Hi motteww, please let us know how can we contact you inside MicroFocus. 
Thank you.
Dorin Bogdan.

2022-02-25 08:12 UTC, motteww commented
> 

Email or teams to: ying.wang17@microfocus.com

2022-02-25 08:14 UTC, Zsolt-Lukacs22 commented
Currently unreviewed, please do not merge.

2022-02-28 11:06 UTC, Zsolt-Lukacs22 requested changes
Please, also plan to resolve most of the CodeClimate analyzer issues and reduce them.

2022-02-28 11:06 UTC, Zsolt-Lukacs22 commented on HpToolsLauncher/TestRunners/GuiTestRunner.cs
> -                    QTPTestCleanup();
Please, discard all changes in GuiTestRunner, unnecessary and interfere with other modifications (causes merge conflict in other PR).

2022-02-28 11:06 UTC, Zsolt-Lukacs22 commented on src/main/java/com/microfocus/application/automation/tools/mc/HttpUtils.java
> +                    obj = (JSONObject) JSONValue.parseStrict(res.toString());
parseStrict() is unnecessary if isValidJson is called on, can only use parse(), or continue using parseStrict() without additional check, but catching more specific exception types, e.g. parseStrict() can throw ParseException, the IO operations can throw IOException.

2022-02-28 11:06 UTC, Zsolt-Lukacs22 commented on src/main/java/com/microfocus/application/automation/tools/mc/Oauth2TokenUtil.java
> +        return true;
I would also add an additional check if all the 3 parts are populated: client, secret, tenant. By default AFAIK, the generated execution token contains all the parts, then if the given token does not contain it is malformed in my opinion.

2022-02-28 11:06 UTC, Zsolt-Lukacs22 commented on src/main/resources/com/microfocus/application/automation/tools/run/RunFromFileBuilder/config.jelly
> +                    <f:radioBlock name="authModel" field="authModel" value="token" checked="${instance.runFromFileModel.authType == 'token' || instance.runFromFileModel.authType == null}" title="Exec
Would introduce a new separate jelly model for this, as an example SpecifyParametersModel in the new PR, or UFTSettingsModel previously. The jelly modifications are duplicated, a new model would resolve this. If you plan to integrate this, please also introduce a separate JS file for the model, extracting all the code from the configure.js, regarding MC.

2022-03-02 05:51 UTC, closed without merging