Store almPassword as a String
jenkinsci/hpe-application-automation-tools-plugin pull request #653
Opened 2024-03-14 15:01 UTC by juanpablo-santos

Please Make sure these boxes are checked before submitting your pull request - Thanks ahead!

- [X] Proper pull request title - concise and clear for others.
- [ ] Proper pull request short description - clear and concise (as it should appear in the Jira ticket) for other developers and users.
- [ ] Proper Jira ticket - Number, Link in pull request description.
- [ ] The PR can is merged on your machine without any conflicts.
- [] The PR can is built on your machine without any (new) warnings.
- [ ] The PR passed sanity tests by you / QA / DevTest / Good Samaritan.
- [ ] Add unit tests with new features.
- [ ] If you added any dependency to the POM - Please update grount

2024-03-15 08:45 UTC, yaroslavafenkin requested changes

2024-03-15 08:45 UTC, yaroslavafenkin commented on src/main/java/com/microfocus/application/automation/tools/model/CredentialsModel.java
> +    private String almPassword;
Sensitive data should not be stored as strings. See https://www.jenkins.io/doc/developer/security/secrets/.

2024-03-15 09:37 UTC, juanpablo-santos commented on src/main/java/com/microfocus/application/automation/tools/model/CredentialsModel.java
> +    private String almPassword;
ouch, fair enough, guess then that the constructor should receive a `Secret` instead? or should a new constructor be provided?

2024-03-15 14:19 UTC, daniel-beck requested changes
This is likely wrong; secrets should not be stored unencrypted in build step configurations.

(Not a maintainer, just org owner.)

2024-08-13 08:22 UTC, daniel-beck reviewed
Code looks reasonable, I recommend this be tested interactively to ensure the Pipeline authoring experience isn't broken.

2025-04-07 10:12 UTC, merged